### ISSUE TITLE
Unable to export (Windows 10, Inkscape 1.2 (dc2aedaf03, 2022-05-15))

### ISSUE THREAD

**Issue by PhoenixWyllow** [nshkurkin/inkscape-export-layer-combos#1]
Hi,
I've tried exporting some layers with your plugin. My settings are as follows:
![image](https://user-images.githubusercontent.com/54237626/178108815-e8f210c1-cee0-4147-bb01-aa0ff78602a3.png)

This is message I get (no icons exported):
```
WARNING:root:Options:` Namespace(input_file='C:\\Users\\wdrpe\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svg1CKSO1', output=<_io.BufferedWriter name='<stdout>'>, ids=['layer4'], selected_nodes=[], path='C:\\Users\\wdrpe\\OneDrive\\Pictures\\MacrodeckIcons\\icons\\', filetype='png', dpi=300.0, ascii=False, negatives=False, lower=True, debug=True, one=False, dry=False)
WARNING:root:Found valid layer 'Frame' with '2' exports, it has 4 children.
WARNING:root:Found valid layer 'Media' with '2' exports, it has 8 children.
WARNING:root:Computed 8 combos:
WARNING:root:  f-media-frame-rec
WARNING:root:Writing SVG to temporary location C:\Users\wdrpe\AppData\Local\Temp\tmpctspya4d.svg
WARNING:root: ... showing layer 'Frame'
WARNING:root: ... showing layer 'Rec'
WARNING:root: ... hiding layer 'Stop'
WARNING:root: ... hiding layer 'Pause'
WARNING:root: ... hiding layer 'Play'
WARNING:root: ... hiding layer 'Forward'
WARNING:root: ... hiding layer 'Backward'
WARNING:root: ... hiding layer 'Scene'
WARNING:root: ... hiding layer 'Sound'
Traceback (most recent call last):
  File "C:\Users\wdrpe\AppData\Roaming\inkscape\extensions\com.ftlgoats.combo.layers\inkscape-export-layer-combos-main\export_layer_combos.py", line 340, in <module>
    _main()
  File "C:\Users\wdrpe\AppData\Roaming\inkscape\extensions\com.ftlgoats.combo.layers\inkscape-export-layer-combos-main\export_layer_combos.py", line 336, in _main
    effect.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 231, in run
    self.save_raw(self.effect())
  File "C:\Users\wdrpe\AppData\Roaming\inkscape\extensions\com.ftlgoats.combo.layers\inkscape-export-layer-combos-main\export_layer_combos.py", line 249, in effect
    self.export_layers(layer_dest_svg_path, show, hide)
  File "C:\Users\wdrpe\AppData\Roaming\inkscape\extensions\com.ftlgoats.combo.layers\inkscape-export-layer-combos-main\export_layer_combos.py", line 308, in export_layers
    doc.write(dest)
  File "src/lxml/etree.pyx", line 2072, in lxml.etree._ElementTree.write
  File "src/lxml/serializer.pxi", line 747, in lxml.etree._tofilelike
  File "src/lxml/serializer.pxi", line 815, in lxml.etree._create_output_buffer
  File "src/lxml/serializer.pxi", line 805, in lxml.etree._create_output_buffer
PermissionError: [Errno 13] Permission denied
```
Any help understanding what's happening would be appreciated.

**Comment by Vincent-LAMBERT** [comment]
Hello,

I found the solution but as this is a first for me (young developer), I am not sure how to make it included in the plugin as it is.

Anyway, here is my solution with inspiration taken from different places on the net. You have to modify the `.py` file to add it a `CustomNamedTemporaryFile` class as presented below.

```
class CustomNamedTemporaryFile: 
    """
    MODIFIED FROM : https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file
    This custom implementation is needed because of the following limitation of tempfile.NamedTemporaryFile:

    > Whether the name can be used to open the file a second time, while the named temporary file is still open,
    > varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).
    """
    def __init__(self, mode='wb', suffix="", delete=True):
        self._mode = mode
        self._delete = delete
        self.suffix = suffix

    def __enter__(self):
        # Generate a random temporary file name
        file_name = os.path.join(tempfile.gettempdir(), os.urandom(24).hex())+self.suffix
        # Ensure the file is created
        open(file_name, "x").close()
        # Open the file in the given mode
        self._tempFile = open(file_name, self._mode)
        return self._tempFile

    def __exit__(self, exc_type, exc_val, exc_tb):
        self._tempFile.close()
        if self._delete:
            os.remove(self._tempFile.name)
```

Then, you modify the `ComboExport.effect` method. The following lines...

```
with tempfile.NamedTemporaryFile(suffix=".svg") as fp_svg:
    layer_dest_svg_path = fp_svg.name
    logit(f"Writing SVG to temporary location {layer_dest_svg_path}")
    self.export_layers(layer_dest_svg_path, show, hide)
    
    if self.options.filetype == "jpeg":
        with tempfile.NamedTemporaryFile(suffix=".png") as fp_png:
            logit(f"Writing PNG to temporary location {fp_png.name}")
            self.export_to_png(layer_dest_svg_path, fp_png.name)
            layer_dest_jpg_path = os.path.join(output_path, f"{label}.jpg")
            logit(f"Writing JPEG to final location {layer_dest_jpg_path}")
            self.convert_png_to_jpeg(fp_png.name, layer_dest_jpg_path)
    else:
        layer_dest_png_path = os.path.join(output_path, f"{label}.png")
        logit(f"Writing PNG to final location {layer_dest_png_path}")
        self.export_to_png(layer_dest_svg_path, layer_dest_png_path)
```

...have to become as below : 

```
# If OS is Windows, use a the CustomNamedTemporaryFile.
if os.name == "nt":
    with CustomNamedTemporaryFile(suffix=".svg") as fp_svg:
        layer_dest_svg_path = fp_svg.name
        logit(f"Writing SVG to temporary location {layer_dest_svg_path}")
        self.export_layers(layer_dest_svg_path, show, hide)

        if self.options.filetype == "jpeg":
            with CustomNamedTemporaryFile(suffix=".png") as fp_png:
                logit(f"Writing PNG to temporary location {fp_png.name}")
                self.export_to_png(layer_dest_svg_path, fp_png.name)
                layer_dest_jpg_path = os.path.join(output_path, f"{label}.jpg")
                logit(f"Writing JPEG to final location {layer_dest_jpg_path}")
                self.convert_png_to_jpeg(fp_png.name, layer_dest_jpg_path)
        else:
            layer_dest_png_path = os.path.join(output_path, f"{label}.png")
            logit(f"Writing PNG to final location {layer_dest_png_path}")
            self.export_to_png(layer_dest_svg_path, layer_dest_png_path)
else : # Otherwise, use the standard NamedTemporaryFile.
    with tempfile.NamedTemporaryFile(suffix=".svg") as fp_svg:
        layer_dest_svg_path = fp_svg.name
        logit(f"Writing SVG to temporary location {layer_dest_svg_path}")
        self.export_layers(layer_dest_svg_path, show, hide)

        if self.options.filetype == "jpeg":
            with tempfile.NamedTemporaryFile(suffix=".png") as fp_png:
                logit(f"Writing PNG to temporary location {fp_png.name}")
                self.export_to_png(layer_dest_svg_path, fp_png.name)
                layer_dest_jpg_path = os.path.join(output_path, f"{label}.jpg")
                logit(f"Writing JPEG to final location {layer_dest_jpg_path}")
                self.convert_png_to_jpeg(fp_png.name, layer_dest_jpg_path)
        else:
            layer_dest_png_path = os.path.join(output_path, f"{label}.png")
            logit(f"Writing PNG to final location {layer_dest_png_path}")
            self.export_to_png(layer_dest_svg_path, layer_dest_png_path)
```

**Comment by BengtER** [comment]
I have today made a fork that implements the suggested fixes plus added fix for the "convert" command to Image Magick that in later versions has been chaged to "magick convert".
